# Generated by Django 3.1 on 2020-08-15 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200815_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovRotativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('parametros', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.parametros')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.veiculo')),
            ],
        ),
    ]
