# Generated by Django 3.1 on 2020-08-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movmensalista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movrotativo',
            name='parametros',
        ),
        migrations.AddField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
