# Generated by Django 3.1 on 2020-08-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200818_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='parametro',
        ),
        migrations.AddField(
            model_name='mensalista',
            name='valor_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
